dist: trusty

language: python

python:
    - '2.7'
    - '3.6'

addons:
  apt:
    packages:
      - python-numpy
      - python3-numpy

before_install:
  - pip install pytest pytest-cov code_extract pylint
  - code_extract README.md test/readme_test.py --filter python

install:
  - pip install .

script:
  - pylint perfplot
  - pylint test/*.py
  - cd test && MPLBACKEND=Agg pytest --cov perfplot

after_success:
  - bash <(curl -s https://codecov.io/bash)
