dist: trusty

language: python

python:
    - '2.7'
    - '3.4'

addons:
  apt:
    packages:
      - python-numpy
      - python3-numpy

before_install:
  - pip install pytest pytest-cov

install:
  - pip install .

script:
  - cd test && MPLBACKEND=Agg pytest --cov perfplot

after_success:
  - bash <(curl -s https://codecov.io/bash)
